name: Super-Linter
run-name: short description
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      run: echo "Here is a test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show remote databases
      - run: 
